/**
 * Which calls take a file path, and which never do. Matched on the last
 * dotted component (`pd.read_csv` → `read_csv`), so aliases do not matter.
 */
export const READ_CALLEES = new Set([
  "open",
  "Path",
  "PurePath",
  "PosixPath",
  "WindowsPath",
  "join",
  "read_csv",
  "read_excel",
  "read_json",
  "read_parquet",
  "read_pickle",
  "read_table",
  "read_feather",
  "read_hdf",
  "loadtxt",
  "genfromtxt",
  "imread",
  "load_img",
  "ImageFolder",
  "listdir",
  "walk",
  "exists",
  "isfile",
  "isdir",
]);
export const WRITE_CALLEES = new Set([
  "savetxt",
  "savefig",
  "to_csv",
  "to_excel",
  "to_json",
  "to_parquet",
  "to_pickle",
  "imwrite",
  "imsave",
  "makedirs",
  "mkdir",
  "save_pretrained",
]);
/** `load` and `save` are only paths for these libraries (spacy.load is a model name). */
export const PATH_LIBS = new Set(["np", "numpy", "torch", "joblib", "pickle", "jnp"]);
export const JOIN_LIKE = new Set(["join", "Path", "PurePath", "PosixPath", "WindowsPath"]);
export const IGNORED_CALLEES = new Set([
  "print",
  "format",
  "endswith",
  "startswith",
  "split",
  "rsplit",
  "replace",
  "strip",
  "rstrip",
  "lstrip",
  "write",
  "add_scalar",
  "add_scalars",
  "add_image",
  "add_text",
  "add_figure",
  "log",
  "info",
  "debug",
  "warning",
  "error",
  "match",
  "search",
  "sub",
  "compile",
  "findall",
  "fullmatch",
  "title",
  "xlabel",
  "ylabel",
  "suptitle",
  "legend",
  "text",
  "annotate",
  "set_title",
  "set_xlabel",
  "set_ylabel",
  "getenv",
  "get",
]);
